source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby "3.1.4"

gem 'cocoapods', '~> 1.16.2'
gem 'activesupport', '>= 6.1.7.3', '< 7.1.0'
gem 'concurrent-ruby', '1.3.4'