version: 2
executorType: docker
jobs:
  build:
    resource_class: large
    working_directory: ~/app
    docker:
      - image: circleci/android:api-28-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1_1-npm-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1_1-npm
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Validate
          command: yarn validate
      - run:
          name: Run Checks
          command: |
            cd android
            chmod +x ./gradlew
            ./gradlew clean && ./gradlew && ./gradlew check
      - save_cache:
          key: v1_1-npm
          paths:
            - node_modules/
      - save_cache:
          key: v1_1-npm-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/

