// flow-typed signature: 19d8ce677e11098c56c2713ac11d8be6
// flow-typed version: <<STUB>>/generate-changelog_v1.7.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'generate-changelog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'generate-changelog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'generate-changelog/lib/cli' {
  declare module.exports: any;
}

declare module 'generate-changelog/lib/file' {
  declare module.exports: any;
}

declare module 'generate-changelog/lib/git' {
  declare module.exports: any;
}

declare module 'generate-changelog/lib/index' {
  declare module.exports: any;
}

declare module 'generate-changelog/lib/package' {
  declare module.exports: any;
}

declare module 'generate-changelog/lib/writer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'generate-changelog/lib/cli.js' {
  declare module.exports: $Exports<'generate-changelog/lib/cli'>;
}
declare module 'generate-changelog/lib/file.js' {
  declare module.exports: $Exports<'generate-changelog/lib/file'>;
}
declare module 'generate-changelog/lib/git.js' {
  declare module.exports: $Exports<'generate-changelog/lib/git'>;
}
declare module 'generate-changelog/lib/index.js' {
  declare module.exports: $Exports<'generate-changelog/lib/index'>;
}
declare module 'generate-changelog/lib/package.js' {
  declare module.exports: $Exports<'generate-changelog/lib/package'>;
}
declare module 'generate-changelog/lib/writer.js' {
  declare module.exports: $Exports<'generate-changelog/lib/writer'>;
}
