name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
          run:
            working-directory: website
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            website
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: website/yarn.lock
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build website
        run: yarn build
      - name: Deploy to GitHub Pages 
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
          keep_files: true